name: CD

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'test'
      - 'stg'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    container:
      image: docker:rc-git
    steps:
    -
      name: Checkout Code
      uses: actions/checkout@v3
    -
      name: Copy CI files to root
      run: |
        cd /app
        cp Devops/auth.json .
        cp Devops/docker-compose.yml .
        cp Devops/Dockerfile .
        cp Devops/wait-for-mysql.sh .
        cp Devops/magento2_module_install.sql .
    -
      name: Build image base for modifications
      run: |
        cd /app
        ls
        docker compose up -d
    -
      name: Activate and setup Plugin
      run: docker ps
    -
      name: Commit and push Docker image
      run: |
        sleep 5 && docker stop magento2_bitnami
        docker login ${{ secrets.DOCKER_ACCOUNT }} -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker commit magento2_bitnami "${{ secrets.DOCKER_ACCOUNT }}/${{ github.repository }}:${{ github.ref }}"
        docker push "${{ secrets.DOCKER_ACCOUNT }}/${{ github.repository }}:${{ github.ref }}"
    - 
      # name: Send deployment webhook to Rancher
      # run: |
      #   BODY='{"push_data":{"tag":"'"${{ github.ref }}"'"},"repository":{"repo_name":"'"${{ secrets.DOCKER_ACCOUNT }}/${{ github.repository }}"'"}}'
      #   curl -X POST ${{ secrets.RANCHER_STG_DEPLOY_URL }} -H 'Content-Type: application/json' -d "${BODY}"
